### ISSUE TITLE
给你点赞！

### ISSUE THREAD

**Issue by jeeyshe** [imoyao/idealyard#7]
顺便说一句， 你怎么不搞个域名啊？

**Comment by imoyao** [comment]
哈哈，看到你的网站了，写得很漂亮。
这个网站只是因为最近项目用到flask，所以用来练手的。而且前端没有响应式布局，在移动端显示丑陋。个人觉得只适合作为框架使用的演示，还不太适合当作一个成熟产品使用。
域名因为国内服务器需要备案，所以没有和本网站绑定而是和[静态网站](https://www.masantu.com/)绑定在一起的。
